// [frontend/src/constants/Strings.js]

export const STRINGS = {
  AUTH: {
    WELCOME_BACK: "Welcome Back",
    SUBTITLE_LOGIN: "Log in to your account",
    EMAIL_LABEL: "Email Address",
    PASSWORD_LABEL: "Password",
    EMAIL_PLACEHOLDER: "example@mail.com",
    PASSWORD_PLACEHOLDER: "********",
    FORGOT_PASSWORD: "Forgot Password?",
    LOGIN_BUTTON: "Log in",
    DONT_HAVE_ACCOUNT: "Don't have an account? ",
    REGISTER_LINK: "Register",
    VALIDATION_ERROR: "Notice",
    FILL_ALL_FIELDS: "Please fill in both email and password",
    LOGIN_FAILED: "Login Failed",
    LOGOUT_CONFIRM_TITLE: "Sign Out",
    LOGOUT_CONFIRM_MSG: "Are you sure you want to sign out?",
    LOGOUT_BUTTON: "Sign Out",
  },
  AI: {
    WELCOME_MESSAGE: "👋 Hello! I'm Eatsy AI — your personalized culinary assistant.\n\nI can suggest meals from your pantry, track calories, guide your cooking, or plan your week.\n\nWhat's on your mind today? 🍽️",
    INPUT_PLACEHOLDER: "Ask Eatsy AI anything...",
    QUICK_PROMPT_TITLE: "SUGGESTED QUESTIONS",
    ONLINE_STATUS: "Online",
    ERROR: "⚠️ Connection error. Please try again!",
  },
  RECIPE: {
    INGREDIENTS: "Ingredients",
    INSTRUCTIONS: "Instructions",
    STEP: "Step",
    PREP_TIME: "TIME",
    DIFFICULTY: "DIFFICULTY",
    CALORIES: "CALORIES",
    SERVINGS: "Servings",
    CHEF_CHOICE: "CHEF'S CHOICE",
    HEALTH_NOTE: "HEALTH NOTE",
    THE_PROFILE: "The Profile",
    ASK_AI_BUTTON: "Ask Eatsy for help...",
  },
  PROFILE: {
    DIETARY_PREFS: "Dietary Preferences",
    ACCOUNT_SECTION: "Account",
    EDIT_PROFILE: "Edit Profile",
  },
  ONBOARDING: {
    STEP_TITLE: "Step",
    OF: "of",
    TOUR_NEXT: "Continue",
    TOUR_SKIP: "Skip Tour",
    STYLE_TITLE: "Your Cooking Style",
    STYLE_SUBTITLE: "This helps us suggest recipes that match your skill and time.",
    GOAL_TITLE: "Your Health Goal",
    GOAL_SUBTITLE: "We'll adjust your daily calorie targets based on this.",
    METRICS_TITLE: "Quick Body Stats",
    METRICS_SUBTITLE: "Just the basics to get your nutrition right.",
    DIET_TITLE: "Dietary Needs",
    DIET_SUBTITLE: "Crucial for safe and personalized meal suggestions.",
    SUCCESS_TITLE: "You're all set",
    SUCCESS_SUBTITLE: "Welcome to a smarter way of eating. Your AI Chef is ready!",
    NEXT_BUTTON: "Next",
    FINISH_BUTTON: "Start Cooking",
    LABEL_WEIGHT: "Weight (kg)",
    LABEL_HEIGHT: "Height (cm)",
    LABEL_CALORIES: "Daily Calorie Target",
    CALORIES_HINT: "Suggested: 1500 - 2500 kcal",
    MEASURE_TITLE: "Measurement System",
    MEASURE_SUBTITLE: "How would you like to see units in recipes?",
    ALLERGY_TITLE: "Allergies & Intolerances",
    ALLERGY_SUBTITLE: "We'll strictly exclude these from suggestions.",
    CUISINE_TITLE: "Favourite Cuisines",
    CUISINE_SUBTITLE: "Help us recommend what you'll love most.",
  },
  COMMON: {
    LOADING: "Loading...",
    LOADING_RECIPES: "Coming up with something delicious...",
    ERROR: "An error occurred",
    SUCCESS: "Success",
    CANCEL: "Cancel",
    SEE_ALL: "See all",
  },
  HOME: {
    GREETING_MORNING: "Good Morning,",
    GREETING_AFTERNOON: "Good Afternoon,",
    GREETING_EVENING: "Good Evening,",
    HERO_TITLE: "Recipe Ideas",
    HERO_SUBTITLE: "What would you like to cook today?",
    CURATED_TITLE: "Curated for you",
    SOMETHING_ELSE: "Something else?",
    LETS_COOK: "Let's Cook",
  }
};
